### ISSUE TITLE
User Menu Line-Height Alignment Issue

### ISSUE THREAD

**Issue by emclaug2** [brightlayer-ui/angular-component-library#419] opened 2022-04-04 16:40 UTC
#### Describe the bug
User Menu Text is not centered anymore.

#### What is the expected behavior?
Text value should be centered.

#### What are the steps to reproduce?
1. Generate a new project using the CLI, auth template, and observe. 
2. You can probably recreate this in the showcase.

#### Screenshots or links to minimum reproduction example
![image](https://user-images.githubusercontent.com/6538289/161591246-fa52d793-5849-42fd-98dd-0aca1866af37.png)

#### Anything else to add?
This is related to either the Angular 13 update or the new Typographies rules we've added; regardless a `line-height: unset` fixes the issue.

**Comment by ektasawant** [comment] 2022-04-05 09:03
<img width="1769" alt="Screenshot 2022-04-05 at 2 32 01 PM" src="https://user-images.githubusercontent.com/10433274/161718895-d8b79edc-94ad-452d-9f51-28179d3df249.png">
Showcase demo is working fine. 

tried to reproduce in cli template but getting following error while `npm start`.
<img width="1023" alt="Screenshot 2022-04-05 at 2 33 30 PM" src="https://user-images.githubusercontent.com/10433274/161719189-7824d3a9-5dff-42ae-8282-f5e664ef67d1.png">

**Comment by ektasawant** [comment] 2022-04-06 05:15
Hi @emclaug2 , able to reproduce issue.
<img width="1233" alt="Screenshot 2022-04-06 at 10 43 19 AM" src="https://user-images.githubusercontent.com/10433274/161900580-07972b14-65fb-4689-8198-3da8da5dc63f.png">

Do we need this mat-h2 class? Since it is overriding font-weight, margin CSS?

**Comment by emclaug2** [comment] 2022-04-06 21:59
@ektasawant Please keep the mat-h2 class & adjust the line-height.

**Comment by ektasawant** [comment] 2022-04-13 09:15
Closing this issue. PR merged https://github.com/brightlayer-ui/angular-component-library/pull/420

**Closed** 2022-04-13 09:15 UTC
Labels: bug
